level = 0
movespeed = 1 + (level*0.05);
dir_x = 0
dir_y = 0
price = 100;
e_health_max = 80 + (level*10);
e_health = e_health_max
range = 300 + (level * 25);
cooldown_max = room_speed * (1 - (level*0.05))
cooldown = cooldown_max
damage = 5 + (level*3);